export const FETCH_SUPPLIERS_SUCCESS = "FETCH_SUPPLIERS_SUCCESS";

export const FETCH_SUPPLIER_DETAILS_SUCCESS = "FETCH_SUPPLIER_DETAILS_SUCCESS";

export const UPDATE_SUPPLIER_SUCCESS = "UPDATE_SUPPLIER_SUCCESS";

export const DELETE_SUPPLIER_SUCCESS = "DELETE_SUPPLIER_SUCCESS";
