export const FETCH_GOODS_ITEMS_SUCCESS = "FETCH_GOODS_ITEMS_SUCCESS";

export const FETCH_GOODS_ITEM_DETAILS_SUCCESS =
    "FETCH_GOODS_ITEM_DETAILS_SUCCESS";

export const UPDATE_GOODS_ITEM_SUCCESS = "UPDATE_GOODS_ITEM_SUCCESS";

export const DELETE_GOODS_ITEM_SUCCESS = "DELETE_GOODS_ITEM_SUCCESS";
