export const FETCH_GOODS_IMPORT_JOBS_BEGIN = "FETCH_GOODS_IMPORT_JOBS_BEGIN";
export const FETCH_GOODS_IMPORT_JOBS_SUCCESS =
    "FETCH_GOODS_IMPORT_JOBS_SUCCESS";
export const FETCH_GOODS_IMPORT_JOBS_FAILURE =
    "FETCH_GOODS_IMPORT_JOBS_FAILURE";
