export const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS";

export const FETCH_CATEGORY_DETAILS_SUCCESS = "FETCH_CATEGORY_DETAILS_SUCCESS";

export const UPDATE_CATEGORY_SUCCESS = "UPDATE_CATEGORY_SUCCESS";

export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";
