<?php

return [
    'company' => [
        'name' => [
            'en' => 'Unstoppable Trading',
            'tc' => '永行貿易有限公司',
        ],
        'phone' => '35686844',
        'fax' => ' 35686344',
        'email' => 'Unstoppable_Trading@hotmail.com',
    ],
    'currencies' => [
        'HKD',
        'TWD',
    ],
    'roles' => [
        [
            'value' => 'ADMIN',
            'permissions' => [
                'salesreport' => true,
                'user' => true,
                'goods' => true,
                'stock' => true,
                'purchase' => true,
                'shipping' => true,
                'supplier' => true,
                'category' => true,
                'warehouse' => true,
                'client' => true,
            ],
        ],
        [
            'value' => 'EMPLOYEE',
            'permissions' => [
                'salesreport' => false,
                'user' => false,
                'goods' => false,
                'stock' => false,
                'shipping' => false,
                'supplier' => false,
                'category' => false,
                'warehouse' => false,
                'client' => false,
            ],
        ],
    ],
    'goods' => [
        'cups' => [
            'A',
            'B',
            'C',
            'D',
            'E',
            'F',
            'G',
        ],
        'sizes' => [
            '32-S',
            '34-M',
            '36-L',
            '38-XL',
            '40-Q',
            '42-EQ',
            '44-Free',
        ],
        'colors' => [
            '什色',
            '卡其',
            '咖啡',
            '墨綠',
            '大紅',
            '天藍',
            '寶藍',
            '摩卡',
            '杏',
            '杏黃',
            '桃紅',
            '棗紅',
            '橙',
            '橙紅',
            '水藍',
            '深杏',
            '深灰',
            '深紫',
            '深綠',
            '深藍',
            '淺咖啡',
            '淺杏',
            '淺灰',
            '淺紫',
            '淺綠',
            '淺藍',
            '淺黃',
            '灰',
            '灰紫',
            '灰綠',
            '灰藍',
            '白',
            '米白',
            '米黃',
            '粉',
            '粉紅',
            '粉紫',
            '粉藍',
            '紅',
            '紅啡',
            '紫',
            '紫灰',
            '紫紅',
            '綠',
            '膚色',
            '芋紫',
            '苧灰',
            '葡萄紫',
            '藍',
            '藍紫',
            '藍綠',
            '豆沙',
            '金',
            '銀',
            '銀灰',
            '青',
            '黃',
            '黑',
            '1#',
            'other',
        ],
    ],
];