export const FETCH_GOODS_CONTENTS_SUCCESS = "FETCH_GOODS_CONTENTS_SUCCESS";

export const FETCH_GOODS_CONTENT_DETAILS_SUCCESS =
    "FETCH_GOODS_CONTENT_DETAILS_SUCCESS";

export const UPDATE_GOODS_CONTENT_SUCCESS = "UPDATE_GOODS_CONTENT_SUCCESS";

export const DELETE_GOODS_CONTENT_SUCCESS = "DELETE_GOODS_CONTENT_SUCCESS";
