export const FETCH_WAREHOUSES_SUCCESS = "FETCH_WAREHOUSES_SUCCESS";

export const FETCH_WAREHOUSE_DETAILS_SUCCESS =
    "FETCH_WAREHOUSE_DETAILS_SUCCESS";

export const UPDATE_WAREHOUSE_SUCCESS = "UPDATE_WAREHOUSE_SUCCESS";

export const DELETE_WAREHOUSE_SUCCESS = "DELETE_WAREHOUSE_SUCCESS";
