export const FETCH_CLIENTS_SUCCESS = "FETCH_CLIENTS_SUCCESS";

export const FETCH_CLIENT_DETAILS_SUCCESS = "FETCH_CLIENT_DETAILS_SUCCESS";

export const UPDATE_CLIENT_SUCCESS = "UPDATE_CLIENT_SUCCESS";

export const DELETE_CLIENT_SUCCESS = "DELETE_CLIENT_SUCCESS";
