export const FETCH_PURCHASES_SUCCESS = "FETCH_PURCHASES_SUCCESS";

export const FETCH_PURCHASE_ITEMS_SUCCESS = "FETCH_PURCHASE_ITEMS_SUCCESS";

export const FETCH_PURCHASE_DETAILS_SUCCESS = "FETCH_PURCHASE_DETAILS_SUCCESS";

export const UPDATE_PURCHASE_SUCCESS = "UPDATE_PURCHASE_SUCCESS";

export const DELETE_PURCHASE_SUCCESS = "DELETE_PURCHASE_SUCCESS";
