export const FETCH_GOODS_SUCCESS = "FETCH_GOODS_SUCCESS";

export const FETCH_GOODS_DETAILS_SUCCESS = "FETCH_GOODS_DETAILS_SUCCESS";

export const UPDATE_GOODS_SUCCESS = "UPDATE_GOODS_SUCCESS";

export const DELETE_GOODS_SUCCESS = "DELETE_GOODS_SUCCESS";
